//
//  DetailWireframe.swift
//  MyPokedex
//
//  Created by Pedro  Rey Simons on 04/03/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator and edited by Pedro Rey Simons.
//

import UIKit

final class DetailWireframe: BaseWireframe {
    var homePresenter:HomePresenter? // References to the parent module
    init(with instance: PokemonEntity) {
        let moduleViewController = DetailViewControllerObjC()
        /* Detail view controller has been implemented in Objective-C for showing skills about working with both languages together in the same project.
         DetailViewControllerObjC is 100% replaceable with the Swift version (not implemented yet). To see a small sample of the Swift<->ObjC interoperability, just uncomment the next line and run again and navigate to a detail screen of any pokemon.*/
        
        /// moduleViewController = DetailViewController()

        super.init(viewController: moduleViewController)
        let interactor = DetailInteractor()
        
        let presenter = DetailPresenter(view: moduleViewController, interactor:  interactor, wireframe: self)
        moduleViewController.presenter = presenter
        interactor.presenter = presenter
        
        //Push selected pokemon data in home to detail presenter.
        presenter.instance = instance
    }
}

extension DetailWireframe: DetailWireframeInterface {
    func refreshHomeData() {
        homePresenter?.refreshData()
    }
}
