//
//  DetailInteractor.swift
//  MyPokedex
//
//  Created by Pedro  Rey Simons on 04/03/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator and edited by Pedro Rey Simons.
//

import Foundation
import CoreData

final class DetailInteractor:NSObject {
    weak var presenter: DetailInteractorOutputInterface?
    private let localDataManager = LocalDataManager.shared
}


extension DetailInteractor: DetailInteractorInputInterface {
    func delete(_ instance: PokemonEntity) {
        localDataManager.deleteInstances(instances: [instance]){ (result) in
            switch result{
                case .success():
                    self.presenter?.deleteFinished(.success(()))
                case .failure(let error):
                    self.presenter?.deleteFinished(.failure(error))
            }
        }
    }
    
    func setCaptured(_ instance: PokemonEntity, isCaptured: Bool) {
        instance.isCaptured = isCaptured
        localDataManager.coreDataStack.saveContext(){ (result) in
            switch result{
                case .success():
                    self.presenter?.setCapturedFinished(.success(()))
                case .failure(let error):
                    self.presenter?.setCapturedFinished(.failure(error))
            }
        }
    }
    
    func extractDetailsFrom(_ instance: PokemonEntity) {
        if let jsonData = instance.jsonData{
            do {
                let jsonDetails = try JSONDecoder().decode(PokemonDetail.self, from: jsonData) as PokemonDetail
                
                let pokemonDetail = PokemonDetail()
                pokemonDetail.id             = Int(instance.id)
                pokemonDetail.name           = instance.resourceName?.capitalized
                pokemonDetail.defaultImage   = instance.image
                pokemonDetail.isCaptured     = instance.isCaptured
                pokemonDetail.height         = jsonDetails.height
                pokemonDetail.weight         = jsonDetails.weight
                pokemonDetail.sprites        = jsonDetails.sprites
                pokemonDetail.types          = jsonDetails.types
                pokemonDetail.stats          = jsonDetails.stats
                self.presenter?.extractDetailsFinished(.success(pokemonDetail))
            } catch  {
                self.presenter?.extractDetailsFinished(.failure(error))
            }
        }
    }
}
