//
//  DetailInterfaces.swift
//  MyPokedex
//
//  Created by Pedro  Rey Simons on 04/03/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator and edited by Pedro Rey Simons.
//

import UIKit

protocol DetailWireframeInterface: WireframeInterface {
    // PRESENTER --> WIREFRAME
    func refreshHomeData()
}

@objc protocol DetailViewInterface: ViewInterface {
    // PRESENTER --> VIEW
    @objc func show(pokemonDetail:PokemonDetail)
    @objc func undoCapturedSwitchChange()

}

@objc protocol DetailPresenterInterface: PresenterInterface {
    // VIEW --> PRESENTER
    @objc func viewDidLoad()
    @objc func rightBarButtonPressed()
    @objc func switchControlChanged(isCaptured:Bool)

}

protocol DetailInteractorInputInterface: InteractorInputInterface{
    // PRESENTER --> INTERACTOR
    func extractDetailsFrom(_ instance: PokemonEntity)
    func delete(_ instance:PokemonEntity)
    func setCaptured(_ instance:PokemonEntity, isCaptured:Bool)

}

protocol DetailInteractorOutputInterface: InteractorOutputInterface{
    // INTERACTOR --> PRESENTER
    func extractDetailsFinished(_ result:Result<PokemonDetail,Error>)
    func deleteFinished(_ result:Result<Void,Error>)
    func setCapturedFinished(_ result:Result<Void,Error>)
}

protocol DetailViewControllerDelegate {
    // DETAIL --> HOME
    func entityDeleted()
    func entityCaptured()
}

