//
//  HomeWireframe.swift
//  MyPokedex
//
//  Created by Pedro  Rey Simons on 01/03/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator and edited by Pedro Rey Simons.
//

import UIKit

final class HomeWireframe: BaseWireframe {
    init() {
        let moduleViewController = HomeViewController()
        super.init(viewController: moduleViewController)
        let interactor = HomeInteractor()
        let presenter = HomePresenter(view:moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
        interactor.presenter = presenter
    }
}

extension HomeWireframe: HomeWireframeInterface {
    func presentDetailModule(for instance: PokemonEntity, with homePresenter:HomePresenter) {
        let detailWireframe = DetailWireframe(with: instance)
        detailWireframe.homePresenter = homePresenter
        DispatchQueue.main.async {
            self.navigationController?.pushWireframe(detailWireframe)
        }
    }
    
    func presentFailureAlert(error: Error) {
        showErrorAlert(with: error.localizedDescription)
    }
}
