//
//  HomeInterfaces.swift
//  MyPokedex
//
//  Created by Pedro  Rey Simons on 01/03/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator and edited by Pedro Rey Simons.
//

import UIKit
import CoreData

protocol HomeWireframeInterface: WireframeInterface {
    // PRESENTER --> WIREFRAME
    func presentDetailModule(for instance: PokemonEntity, with homePresenter:HomePresenter)
    func presentFailureAlert(error:Error)
}

protocol HomeViewInterface: ViewInterface {
    // PRESENTER --> VIEW
    func push(data:[PokemonEntity])
    func reloadCollectionView()
    func startActivity()
    func stopActivity()
}

protocol HomePresenterInterface: PresenterInterface {
    // VIEW --> PRESENTER
    func viewDidLoad()
    func rightBarButtonPressed()
    func didSelect(_ instance:PokemonEntity)
    func refreshData()

}

protocol HomeInteractorInputInterface: InteractorInputInterface{
    // PRESENTER --> INTERACTOR
    func fetchData()
    func resetDataBase()
}

protocol HomeInteractorOutputInterface: InteractorOutputInterface{
    // INTERACTOR --> PRESENTER 
    func fetchDataFinished(_ result:Result<[PokemonEntity],Error>)
    func resetDataBaseFinished(_ result:Result<Void,Error>)

}
