//
//  SplashWireframe.swift
//  MyPokedex
//
//  Created by Pedro  Rey Simons on 01/03/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator and edited by Pedro Rey Simons.
//

import UIKit

final class SplashWireframe: BaseWireframe {
    init() {
        let moduleViewController = SplashViewController()
        super.init(viewController: moduleViewController)
        let interactor = SplashInteractor()
        let presenter = SplashPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
        interactor.presenter = presenter
    }
}

extension SplashWireframe: SplashWireframeInterface {
    func presentFailureAlert(error: Error, completion: @escaping () -> Void) {
        let action = UIAlertAction.init(title: NSLocalizedString("Continue", comment: "Continue without data"), style: .default) { (_) in
            completion()
        }
        showAlert(with: "Error", message: error.localizedDescription, actions: [action])
    }
    
    func presentHomeModule() {
        DispatchQueue.main.async {
            self.navigationController?.pushWireframe(HomeWireframe())
        }
    }
}
