//
//  SplashPresenter.swift
//  MyPokedex
//
//  Created by Pedro  Rey Simons on 01/03/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator and edited by Pedro Rey Simons.
//

import Foundation

final class SplashPresenter {
    private unowned let view:   SplashViewInterface
    private let interactor:     SplashInteractorInputInterface
    private let wireframe:      SplashWireframeInterface
    
    init(view:      SplashViewInterface,
         interactor:SplashInteractorInputInterface,
         wireframe: SplashWireframeInterface) {
        self.view       = view
        self.interactor = interactor
        self.wireframe  = wireframe
    }
}

extension SplashPresenter: SplashPresenterInterface {
    func viewDidLoad(){
        interactor.requestAndSaveDataIfNeeded()
    }
}

extension SplashPresenter: SplashInteractorOutputInterface {
    func requestAndSaveDataIfNeededFinished(_ result: Result<Void, Error>) {
        switch result {
            case .success():
                wireframe.presentHomeModule()
            case .failure(let error):
                wireframe.presentFailureAlert(error: error) {
                    self.wireframe.presentHomeModule()
                }
        }
    }
}



