//
//  SplashViewController.swift
//  MyPokedex
//
//  Created by Pedro  Rey Simons on 01/03/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator and edited by Pedro Rey Simons.
//

import UIKit

final class SplashViewController: UIViewController {
    var presenter: SplashPresenterInterface!
    
    //MARK: - Lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        setupNavigationController()
        setupImageView()
        presenter.viewDidLoad()
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        navigationController?.navigationBar.isHidden = false
    }
    
    func setupNavigationController(){
        navigationController?.navigationBar.isHidden = true
        navigationController?.navigationBar.isTranslucent = false
        navigationController?.view.backgroundColor = ThemeManager.currentTheme().tertiaryColor
        navigationController?.navigationBar.barTintColor = ThemeManager.currentTheme().tertiaryColor
        navigationController?.navigationBar.tintColor = ThemeManager.currentTheme().titleTextColor
    }
    
    func setupImageView(){
        let imageView = UIImageView(image: UIImage(named: Constants.Images.myPokedex))
        imageView.contentMode = .scaleAspectFit
        
        view.addSubview(imageView)
        imageView.anchor(top: view.safeAreaLayoutGuide.topAnchor,
                         leading: view.safeAreaLayoutGuide.leadingAnchor,
                         bottom: view.safeAreaLayoutGuide.bottomAnchor,
                         trailing: view.safeAreaLayoutGuide.trailingAnchor,
                         centerX: nil,
                         centerY: nil,
                         padding: UIEdgeInsets(top: 16, left: 16, bottom: 16, right: 16),
                         size: .zero)


    }
}

extension SplashViewController: SplashViewInterface {
}
