//
//  SplashInteractor.swift
//  MyPokedex
//
//  Created by Pedro  Rey Simons on 01/03/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator and edited by Pedro Rey Simons.
//

import Foundation

final class SplashInteractor {
    weak var presenter: SplashInteractorOutputInterface?
    private let operatorManager = OperationsManager()
    private let localDataManager = LocalDataManager.shared
}

// MARK: - SplashInteractorInputInterface
extension SplashInteractor: SplashInteractorInputInterface {
    func requestAndSaveDataIfNeeded(){
        if localDataManager.firsDataLoadedStatus == true {
            //Data is already locally stored -> Load Home 
            self.presenter?.requestAndSaveDataIfNeededFinished(.success(()))
        } else {
            //Fetch API and save answer. Then load Home
            operatorManager.getAndSaveData { (result) in
                switch result{
                    case .success(_):
                        //firsDataLoadedStatus save in UserDefaults. Next app launch won't need API call.
                        self.localDataManager.firsDataLoadedStatus = true
                        self.presenter?.requestAndSaveDataIfNeededFinished(.success(()))
                    case .failure(let error):
                        self.presenter?.requestAndSaveDataIfNeededFinished(.failure(error))
                }
            }
        }
    }
}
