//
//  SplashInterfaces.swift
//  MyPokedex
//
//  Created by Pedro  Rey Simons on 01/03/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator and edited by Pedro Rey Simons.
//

import UIKit

protocol SplashWireframeInterface: WireframeInterface {
    // PRESENTER --> WIREFRAME
    func presentHomeModule()
    func presentFailureAlert(error:Error,completion:@escaping()->Void)
}

protocol SplashViewInterface: ViewInterface {
    // PRESENTER --> VIEW
}

protocol SplashPresenterInterface: PresenterInterface {
    // VIEW --> PRESENTER
    func viewDidLoad()
}

protocol SplashInteractorInputInterface: InteractorInputInterface{
    // PRESENTER --> INTERACTOR
    func requestAndSaveDataIfNeeded()
}

protocol SplashInteractorOutputInterface: InteractorOutputInterface{
    // INTERACTOR --> PRESENTER
    func requestAndSaveDataIfNeededFinished(_ result:Result<Void,Error>)
}
