//
//  DetailViewController.swift
//  MyPokedex
//
//  Created by Pedro  Rey Simons on 04/03/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator and edited by Pedro Rey Simons.
//

import UIKit

final class DetailViewController: UIViewController {
    var presenter: DetailPresenterInterface!

    //MARK: - Lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        setupInfoLabel()
    }
    
    func setupInfoLabel(){
        let info:UILabel = UILabel.init()
        info.text = "Swift view not implemented.\nSwitch to good Ol' Objective-C version."
        info.numberOfLines = 0
        info.textColor = UIColor.red
        info.textAlignment = .center
        view.addSubview(info)
        info.anchor(top: nil, leading: nil, bottom: nil, trailing: nil, centerX: view.centerXAnchor, centerY: view.centerYAnchor)
    }
}

extension DetailViewController: DetailViewInterface {
    func undoCapturedSwitchChange() {
        return
    }

    func show(pokemonDetail: PokemonDetail) {
        return
    }
    
}


